Repository Garodden/keyboard-arena, pull requests merged in 2024-04, with the labels that each got.

#38 Feat: (마이페이지) 참전한 아레나 전체 조회 api
  src/main/java/com/example/KeyboardArenaProject/controller/user/MyPageController.java
  src/main/java/com/example/KeyboardArenaProject/dto/mypage/MyArenaResponse.java
  src/main/java/com/example/KeyboardArenaProject/repository/ClearedRepository.java
  src/main/java/com/example/KeyboardArenaProject/service/user/MyPageService.java
  src/main/resources/static/js/MyPageGetBoardDetails.js
  src/main/resources/templates/myArenas.html
  src/main/resources/templates/mypage.html
Labels: feat

#39 Feat: 댓글 단 게시물 전체 조회 api 구현
  src/main/java/com/example/KeyboardArenaProject/controller/user/MyPageController.java
  src/main/java/com/example/KeyboardArenaProject/dto/mypage/MyCommentedBoardsResponse.java
  src/main/java/com/example/KeyboardArenaProject/repository/CommentRepository.java
  src/main/java/com/example/KeyboardArenaProject/repository/UserRepository.java
  src/main/java/com/example/KeyboardArenaProject/service/user/MyPageService.java
  src/main/java/com/example/KeyboardArenaProject/service/user/UserService.java
  src/main/resources/templates/commentBoards.html
  src/main/resources/templates/mypage.html
Labels: feat

#48 Feat: 로그인, 회원가입 UI 구현
  src/main/java/com/example/KeyboardArenaProject/controller/arena/ArenaController.java
  src/main/java/com/example/KeyboardArenaProject/controller/freeBoard/FreeBoardController.java
  src/main/java/com/example/KeyboardArenaProject/controller/user/UserController.java
  src/main/java/com/example/KeyboardArenaProject/dto/freeBoard/FreeBoardWriteRequest.java
  src/main/java/com/example/KeyboardArenaProject/entity/Board.java
  src/main/java/com/example/KeyboardArenaProject/entity/Comment.java
  src/main/java/com/example/KeyboardArenaProject/entity/User.java
  src/main/java/com/example/KeyboardArenaProject/service/arena/ArenaService.java
  src/main/java/com/example/KeyboardArenaProject/service/user/UserService.java
  src/main/java/com/example/KeyboardArenaProject/utils/user/GenerateIdUtils.java
  src/main/java/com/example/KeyboardArenaProject/utils/user/GeneratePwUtils.java
  src/main/java/com/example/KeyboardArenaProject/utils/user/UserTopBarInfoUtil.java
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/signup.css
  src/main/resources/static/js/user/Signup.js
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: UI

#56 Feat: 마이페이지 홈UI
  src/main/resources/static/css/user/mypage.css
  src/main/resources/templates/mypage.html
Labels: UI

#61 Feat: (마이페이지) 참전한 아레나 전체 조회, 댓글 쓴 게시글 전체 조회 ui 수정
  src/main/java/com/example/KeyboardArenaProject/controller/user/MyPageController.java
  src/main/java/com/example/KeyboardArenaProject/controller/user/UserViewController.java
  src/main/java/com/example/KeyboardArenaProject/dto/mypage/MyCommentedBoardsResponse.java
  src/main/java/com/example/KeyboardArenaProject/repository/CommentRepository.java
  src/main/java/com/example/KeyboardArenaProject/service/user/MyPageService.java
  src/main/resources/static/css/mypage/MyPageBoards.css
  src/main/resources/static/css/mypage/MypageMenu.css
  src/main/resources/static/js/mypage/MyPageGetBoardDetails.js
  src/main/resources/templates/commentBoards.html
  src/main/resources/templates/home.html
  src/main/resources/templates/likedBoards.html
  src/main/resources/templates/myArenas.html
Labels: UI

#75 Fix: 마이페이지 작성한 글 전체 조회 ui 수정, 회원가입 api 예외처리 추가
  src/main/java/com/example/KeyboardArenaProject/controller/user/UserController.java
  src/main/java/com/example/KeyboardArenaProject/dto/mypage/MyArenaResponse.java
  src/main/java/com/example/KeyboardArenaProject/entity/User.java
  src/main/java/com/example/KeyboardArenaProject/service/user/UserService.java
  src/main/resources/templates/myboards.html
Labels: fix, UI

#76 Feat: 마이페이지 비밀번호 변경 유효성 검사 추가(새로운 비밀번호, 새로운 비밀번호 확인)
  src/main/resources/static/css/user/changePw.css
  src/main/resources/static/js/user/ChangePw.js
  src/main/resources/templates/changePw.html
Labels: feat, UI
